[package]
name = "quantnight-frontend"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "quantnight_frontend_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
mongodb = { version = "2.8", features = ["tokio-runtime"] }
bson = "2"
tokio = { version = "1", features = ["full"] }
futures = "0.3"       # ✅ 用于 join! 并发
futures-util = "0.3"  #提供mongodb的异步流迭代方法
anyhow = "1.0"
chrono = { version = "0.4.41", features = ["serde"] }   #提供后端日期, 时间计算
regex = "1.11.1"  #提供正则匹配的转义功能
once_cell = "1.21.3"
log = "0.4.27"
env_logger = "0.11.8"
config = "0.13"  # 提供脚本信息单独配置的功能
toml = "0.8"  # 用于解析 TOML 配置文件


